services:
  nginx:
    image: nginx
    ports:
        - 8080:80
    volumes:
        - .:/var/www
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - php

  php:
    build: .docker/php
    ports:
        - 5173:5173
    volumes:
        - .:/var/www:cached

  postgres:
    image: postgres:17
    ports:
        - 5432:5432
    volumes:
        - .docker/postgres/data:/var/lib/postgresql/data
        - .docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_USER=comrade
        - POSTGRES_PASSWORD=comrade
        - POSTGRES_DB=comrade_connect_mvp

  mailpit:
    image: axllent/mailpit:latest
    ports:
    - 8025:8025
    - 1025:1025
